theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "battery"
upower = false
format = "{percentage}% {time}"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "backlight"

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
